//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizes.DataBase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArrayNamesR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArrayNamesR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quizes.DataBase.ArrayNamesR", typeof(ArrayNamesR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AanwezighedenSportClubPerPersoon|{true, false, false}.
        /// </summary>
        internal static string AanwezighedenSportClubPerPersoon {
            get {
                return ResourceManager.GetString("AanwezighedenSportClubPerPersoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfstandenNaarPlaneten|{214.61, 684.61, 4568.12}.
        /// </summary>
        internal static string AfstandenNaarPlaneten {
            get {
                return ResourceManager.GetString("AfstandenNaarPlaneten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfstandNaarSteden|{23, 70.5, 66.5} .
        /// </summary>
        internal static string AfstandNaarSteden {
            get {
                return ResourceManager.GetString("AfstandNaarSteden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfabet|{&apos;A&apos;, &apos;B&apos;, &apos;C&apos;}.
        /// </summary>
        internal static string Alfabet {
            get {
                return ResourceManager.GetString("Alfabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntwoordenOpQuiz|{true, true, false}.
        /// </summary>
        internal static string AntwoordenOpQuiz {
            get {
                return ResourceManager.GetString("AntwoordenOpQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AantalAppelen|{5, 3, 0}.
        /// </summary>
        internal static string Apples {
            get {
                return ResourceManager.GetString("Apples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeenderenPerZoogdier|{126, 456, 345}.
        /// </summary>
        internal static string Beenderen {
            get {
                return ResourceManager.GetString("Beenderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlaszijdenPerBoek|{120, 500, 345}.
        /// </summary>
        internal static string BladzijdenPerBoek {
            get {
                return ResourceManager.GetString("BladzijdenPerBoek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouwjaren|{1990, 1880, 1994}.
        /// </summary>
        internal static string Bouwjaren {
            get {
                return ResourceManager.GetString("Bouwjaren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagen|{&quot;Maandag&quot;, &quot;Dinsdag&quot;, &quot;Woensdag&quot;}.
        /// </summary>
        internal static string Dagen {
            get {
                return ResourceManager.GetString("Dagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DagenPerMaand|{31, 30, 31}.
        /// </summary>
        internal static string DagenPerMaand {
            get {
                return ResourceManager.GetString("DagenPerMaand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuurFilms|{120.5, 60.6, 50}.
        /// </summary>
        internal static string DuurFlms {
            get {
                return ResourceManager.GetString("DuurFlms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EersteLettersVanNaam|{&apos;K&apos;, &apos;P&apos;, &apos;L&apos;}.
        /// </summary>
        internal static string EersteLettersVanNaam {
            get {
                return ResourceManager.GetString("EersteLettersVanNaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films|{&quot;Stalker&quot;, &quot;Disconnect&quot;, &quot;Her&quot;}.
        /// </summary>
        internal static string FilmLijst {
            get {
                return ResourceManager.GetString("FilmLijst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleuren|{&quot;Blauw&quot;, &quot;Groen&quot;, &quot;Rood&quot;}.
        /// </summary>
        internal static string Kleuren {
            get {
                return ResourceManager.GetString("Kleuren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeftijden|{20, 44, 82}.
        /// </summary>
        internal static string Leeftijd {
            get {
                return ResourceManager.GetString("Leeftijd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lengtes|{1.70, 1.80, 1.75}.
        /// </summary>
        internal static string Lengtes {
            get {
                return ResourceManager.GetString("Lengtes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LonenWerknemers|{1800.15, 2300.45, 1904.6}.
        /// </summary>
        internal static string LonenWerknemers {
            get {
                return ResourceManager.GetString("LonenWerknemers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maanden|{&quot;januari&quot;, &quot;fabruari&quot;, &quot;maart&quot;}.
        /// </summary>
        internal static string Maanden {
            get {
                return ResourceManager.GetString("Maanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namen|{&quot;Perfidia&quot;, &quot;Hilda&quot;, &quot;Samanta&quot;}.
        /// </summary>
        internal static string Namen {
            get {
                return ResourceManager.GetString("Namen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrijsDranken|{3.30, 3.30, 4.50}.
        /// </summary>
        internal static string PrijsDrank {
            get {
                return ResourceManager.GetString("PrijsDrank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijzen|{1200.15, 5.5, 7894.4}.
        /// </summary>
        internal static string Prijzen {
            get {
                return ResourceManager.GetString("Prijzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrijzenMenuInRestaurant|{16.50, 22.60, 24.3}.
        /// </summary>
        internal static string PrijzenMenuInRestaurant {
            get {
                return ResourceManager.GetString("PrijzenMenuInRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RamenPerGebouw|{10, 8, 12}.
        /// </summary>
        internal static string RamenPerGebouw {
            get {
                return ResourceManager.GetString("RamenPerGebouw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperaturen|{37.3, 18.3, 22.2}.
        /// </summary>
        internal static string Temperaturen {
            get {
                return ResourceManager.GetString("Temperaturen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VolumeKamersHuis|{55.5, 73.6, 15.5}.
        /// </summary>
        internal static string VolumeKamersHuis {
            get {
                return ResourceManager.GetString("VolumeKamersHuis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaardeEuroDagen|{1.5464, 1.4456, 1.5031} .
        /// </summary>
        internal static string waardeEuroPerDag {
            get {
                return ResourceManager.GetString("waardeEuroPerDag", resourceCulture);
            }
        }
    }
}
